#!/bin/bash

function failCommit() {
    tput setaf 1
    echo "----------------------------------------"
    echo "FATAL ERROR: $1"
    echo "----------------------------------------"
    tput sgr0
    exit 1
}


if git-rev-parse --verify HEAD >/dev/null 2>&1 ; then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=bbd0d0446c4c4c97f2a72406d9540ca1e2d68c3f
fi

# Remove all of the trailing whitespace in this commit
for FILE in `exec git diff-index --check --cached $against -- | sed '/^[+-]/d' | sed -E 's/:[0-9]+:.*//' | uniq` ; do
    sed -i '' -E 's/[[:space:]]*$//' "$FILE"
    git add $FILE
done

echo 'Running flake8...'
result=$(make lint)
if [ $? != 0 ]; then
    echo "$result"
    echo ''
    echo 'lint fail'
    lintFailed=1
    failCommit "Lint Errors"
fi

echo 'Running Tests...'
result=$(make testing)
if [ $? != 0 ]; then
    echo "$result"
    echo ''
    echo 'Tests fail'
    testsFailed=1
    failCommit "Test Errors"
fi

if [[ $testsFailed || $lintFailed ]]; then
    failCommit "Unable To Commit"
fi
